version: '3.8'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
  migration:
    build: .
    command: npm run db:migrate
    depends_on:
      - db
    networks:
      - app-network
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_URL=mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl={"rejectUnauthorized":true}
      - DB_DB=${DB_NAME}
    depends_on:
      - migration
    restart: on-failure
    command: npm run server:start
    networks:
      - app-network
  
networks:
  app-network:
volumes:
  db-data:
