version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=dolsys
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
  migration:
    build: .
    restart: on-failure
    command: npm run db:migrate
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_URL=mysql://root:test@db:3306/dolsys?ssl={"rejectUnauthorized":false}
      - DB_DB=dolsys
    networks:
      - app-network
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_URL=mysql://root:test@db:3306/dolsys?ssl={"rejectUnauthorized":false}
      - DB_DB=dolsys
    depends_on:
      - migration
    restart: on-failure
    command: npm run server:start
    networks:
      - app-network
  
networks:
  app-network:
volumes:
  db-data:
