name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://dolsys.tech
    steps:
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PASS }}
        script: |
          cd dolsys
          git pull
          ./prep.sh
          pm2 restart 0
